[project]
name = "audio-consistency-models"
version = "0.1.0"
description = "consistency modellling"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets==2.21.0",
    "librosa",
    "lightning",
    "soundfile",
    "torch>=2.9.1",
    "torchaudio",
    "torchdiffeq",
    "transformers",
    "wandb",
    "ema-pytorch",
    "random-word",
    "comet-ml",
    "einops"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["ct*"]

[project.optional-dependencies]
dev = ["pytest", "black", "isort", "flake8", "mypy"]
training = ["wandb", "datasets"]

[project.urls]
Source = "https://github.com/odunola499/audio-consistency-gym"

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 88